version: 2
jobs:
  build:
    docker:
      - image: quramy/node-nightmare
        environment:
          DISPLAY: ":99"
          GOOGLE_APPLICATION_CREDENTIALS: "/root/gcloud-service-key.json"
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: yarn --pure-lockfile
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Bootstrap packages
          command: yarn run bootstrap
      - run:
          name: Lint
          command: yarn run lint
      - run:
          name: Test
          command: |
            xvfbd start
            yarn run test
            xvfbd stop
