version: 2
jobs:
  build:
    docker:
      - image: quramy/node-nightmare
        environment:
          DISPLAY: ":99"

    working_directory: ~/repo

    steps:

      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-

      - run: yarn --frozen-lockfile

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - run: yarn run bootstrap
      - run: yarn run lint

      - run:
          name: Test
          command: |
            xvfbd start
            yarn run test
            xvfbd stop

workflows:
  version: 2
  reg_gh_app_pipeline:
    jobs:
      - build:
        filters:
          branches:
            ignore:
              - gh-pages

